### ISSUE TITLE
Detecting deleted ports

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#23]
### update 2020.07.27

https://devgit.freshports.org/editors/nvi2-port/ is an example of this: the xml -

```
        <FILES>
            <FILE Action="Add" Revision="543502" Path="head/editors/nvi2/"></FILE>
            <FILE Path="head/editors/nvi2-port/" Action="Remove" Revision="543502"></FILE>
            <FILE Path="head/editors/Makefile" Action="Modify" Revision="543502"></FILE>
        </FILES>
```

Analysis here: https://twitter.com/DLangille/status/1287861346801987585

Now I think it's a matter of coding.  We have what we need.

NOTE: the commit was done in svn and then replicated in git.

An `svn mv` was used, I am sure of it. I have asked the committer for confirmation.

I've done a test 'git mv'.  The log does not show the file disappearing. It is not mentioned at all. https://git.langille.org/dvl/testing-git-mv/commit/1e3da16d82f4a43be42b9631c6c2a0226a24c25f

I am having trouble detecting a port delete or copy. Under subversion, as seen at https://svnweb.freebsd.org/ports?view=revision&revision=542761, you get a deleted notice:

`head/devel/kf5-kcrash/files/ | deleted`

In the email (https://docs.freebsd.org/cgi/getmsg.cgi?fetch=1326960+0+current/svn-ports-head) this turns up as: head/net/kdav/ under Deleted.

In git, it does not, from what I can tell. I can find:

```
$ grep net/kda 2020.07.21.17.15.38.000000.d016c9140a6e4b7627d26485926a659f2686185d.xml
- net/kdav became a framework and was therefore moved to net/kf5-kdav.
      <FILE Action="Delete" Path="net/kdav/distinfo"/>
      <FILE Action="Rename" Path="net/kdav/Makefile" Destination="net/kf5-kdav/Makefile"/>
      <FILE Action="Rename" Path="net/kdav/pkg-plist" Destination="net/kf5-kdav/pkg-plist"/>
```

The [github.com commit](https://github.com/freebsd/freebsd-ports/commit/d016c9140a6e4b7627d26485926a659f2686185d)

The [cgit-beta.freebsd.org](https://cgit-beta.freebsd.org/ports/commit/?id=ed6418531fb2e8a1fbee24f381a5109cd77bda7a)

(Sorry, the above is the XML generated by https://github.com/FreshPorts/git_proc_commit/blob/master/git-to-freshports/git-to-freshports-xml.py)

Knowing that a file has been deleted within a commit is vital. Detecting it from within the commit log is the optimal approach. Does anything have a suggestion here?

I can see that the `Makefile` & `pkg-plist` have been renamed, and `distinfo` has been deleted. Perhaps it's just a matter of changing my approach to pay attention to such things. However, this does not yet sound like a solid plan.

I welcome suggestions for something I have missed in the git interface please.

**Comment by dlangille** [comment]
@skozlov404 I'm hoping you know a way.  I've posted this to the [FreeBSD git mailing list](https://lists.freebsd.org/pipermail/freebsd-git/2020-July/thread.html)

**Comment by dlangille** [comment]
```
[Jul 22 09:09]  <@dvl> From https://cgit-beta.freebsd.org/ports/commit/?id=ed6418531fb2e8a1fbee24f381a5109cd77bda7a
[Jul 22 09:09]  <@dvl> this may be the information I need to conclude a delete:
[Jul 22 09:09]  <@dvl> diff --git a/net/kdav/Makefile b/net/kf5-kdav/Makefile
[Jul 22 09:09]  <@dvl> index de28b840b5a1..34316f5603d2 100644
[Jul 22 09:09]  <@dvl> --- a/net/kdav/Makefile
[Jul 22 09:09]  <@dvl> +++ b/net/kf5-kdav/Makefile
```

**Comment by jgbarah** [comment]
I'm not sure if you're still looking for a solution for this, but I cannot reproduce the issue. I'm using `perceval`, that you can install as a pip package (see below).

When I run Perceval for your test repo, I see:

```
$ perceval git https://git.langille.org/dvl/testing-git-mv.git
...
{
    "backend_name": "Git",
    "backend_version": "0.12.0",
    "category": "commit",
    "classified_fields_filtered": null,
    "data": {
        "Author": "Dan Langille <dan@langille.org>",
        "AuthorDate": "Tue Jul 21 20:40:18 2020 -0400",
        "Commit": "Dan Langille <dan@langille.org>",
        "CommitDate": "Tue Jul 21 20:40:18 2020 -0400",
        "commit": "1e3da16d82f4a43be42b9631c6c2a0226a24c25f",
        "files": [
            {
                "action": "A",
                "added": "1",
                "file": "Second",
                "indexes": [
                    "0000000",
                    "7fbf76e"
                ],
                "modes": [
                    "000000",
                    "100644"
                ],
                "removed": "0"
            }
        ],
        "message": "git mv First Second",
        "parents": [
            "c279a20dcc8e482c435d13478c5f01b427dd84ab"
        ],
        "refs": [
            "HEAD -> refs/heads/master"
        ]
    },
...
```
This is the JSON output that Perceval produces for the second of your commits. You can say how it only detects "Second" as a file touched by the commit, and nothing else.

But if i try to reproduce a git repo the way i understand you produced yours, I find a different output. First, I reproduce it as:

```
$ mkdir test
$ cd test
$ git init
...produce file First...
$ git add First
$ git commit .
$ git mv First Second
$ git commit .
```

And now, the output by Perceval is as follows (I uploaded the repo to GitHub so that you can check it):

```
$ perceval git https://github.com/jgbarah-tests/git-mv-test.git
...
{
    "backend_name": "Git",
    "backend_version": "0.12.0",
    "category": "commit",
    "classified_fields_filtered": null,
    "data": {
        "Author": "Jesus M. Gonzalez-Barahona <jgb@gsyc.es>",
        "AuthorDate": "Wed Jul 22 20:33:46 2020 +0200",
        "Commit": "Jesus M. Gonzalez-Barahona <jgb@gsyc.es>",
        "CommitDate": "Wed Jul 22 20:33:46 2020 +0200",
        "commit": "9f7853b80472d0a7c8a686795b5ed03957f0a780",
        "files": [
            {
                "action": "R100",
                "added": "0",
                "file": "First",
                "indexes": [
                    "5597624",
                    "5597624"
                ],
                "modes": [
                    "100644",
                    "100644"
                ],
                "newfile": "Second",
                "removed": "0"
            }
        ],
        "message": "git mv First Second",
        "parents": [
            "f001532c2ce01f2cf10eb472730856fa573d7a3a"
        ],
        "refs": [
            "HEAD -> refs/heads/master"
        ]
    },
    "origin": "https://github.com/jgbarah-tests/git-mv-test.git",
    "perceval_version": "0.12.24",
    "search_fields": {
        "item_id": "9f7853b80472d0a7c8a686795b5ed03957f0a780"
    },
    "tag": "https://github.com/jgbarah-tests/git-mv-test.git",
    "timestamp": 1595443534.028398,
    "updated_on": 1595442826.0,
    "uuid": "0bd221696a931bd7dd6987ca9548bfd0baa65914"
}
...
``` 

Again, only second commit, which is the one corresponding to `git mv First Second`. But now, you may notice `"newfile": "Second",`, which is signallying that this file is a "new file" `Second`, but also `"file": "First",` which shows the previous name of the file. So, in short, this is Perceval telling that `First` was moved to `Second`. Which is different from your setup.

So, I wonder how you produced your git repo... 

Final note: Perceval is basically querying git for all metainformation, so the same data can be obtained from git directly, but I'm more familiar with Perceval for these matters. If you want to reproduce my actions, just create a Python3 virtual enviornment, activate it, install Perceval, and you're ready to go:

```
$ python3 -m venv /tmp/perceval
$ source /tmp/perceval/bin/activate
(perceval) $ pip install perceval
...
```

**Comment by dlangille** [comment]
> So, I wonder how you produced your git repo...

If I recall correctly, I went to https://git.langille.org, clicked on + to create a repo - which then produced these instructions:

```
touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin git@git.langille.org:dvl/testing1.git
git push -u origin master
```

Then I `touch First`, added content, commit, push, `git mv`, commit, push.

**Comment by jgbarah** [comment]
Wait a moment. You mean you first committed, then touched First, then `git mv First Second`? If that's the case, it is normal that Perceval (nor other tool) detects it as a move, since the move happened between two commits. The first one has not `First`, and the second one has only `Second`... This is consistent with what I'm seeing with Perceval.

If you are trying to detect `git mv` for files that were not present in the previous commit, I think you're out of luck: AFAIK, they are only tracked as snapshots at commit time.

**Comment by jgbarah** [comment]
I'm reproducing your process:

```
$ touch README.md
$ git init
Initialized empty Git repository in /home/jgb/test-2/.git/
$ git add README.md 
$ git commit -m "first commit"
[master (root-commit) fa0fe17] first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
$ touch First
$ vi First 
$ git add First
$ git commit -m "Added First"
[master 9bbdbba] Added First
 1 file changed, 1 insertion(+)
 create mode 100644 First
$ git mv First Second
$ git commit -m "Moved to Second"
[master dcbc6cb] Moved to Second
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename First => Second (100%)
```

And now, I run Perceval. And get the same result as above (detection of the mv):

```
       "files": [
            {
                "action": "R100",
                "added": "0",
                "file": "First",
                "indexes": [
                    "50f4cd2",
                    "50f4cd2"
                ],
                "modes": [
                    "100644",
                    "100644"
                ],
                "newfile": "Second",
                "removed": "0"
            }
```

Re-reading the procedure, and looking at your repo, I see that in your description of the procedure there are three commits, but in the repo there are only two. If for any reason you commited `README.md`, then created `First`, then `git mv First Second`, and only then committed again, the result would be consistent with what we see in your repo. I suggest that you repeat it, in case that still matters.

**Comment by dlangille** [comment]
Detection of newfiles is OK I think.

It's knowing that the file has disappeared. That's the tricky part. That is vital to what I'm trying to do.

**Comment by skozlov404** [comment]
> 
> 
> @skozlov404 I'm hoping you know a way. I've posted this to the [FreeBSD git mailing list](https://lists.freebsd.org/pipermail/freebsd-git/2020-July/thread.html)

Hi @dlangille , sorry I'm kinda swamped right now, I'll take a look at this on the weekend.

**Comment by jgbarah** [comment]
> Detection of newfiles is OK I think.
> 
> It's knowing that the file has disappeared. That's the tricky part. That is vital to what I'm trying to do.

Do you have an example that doesn't work? I've never noticed that, and I've been doing some tests tonight to further check it, but I couldn't find a fail scenario. If I just delete the file, I get a delete action in the log. If I move it somewhere else, I get a move action in the log, with the old and the new name.

**Comment by dlangille** [comment]
There are two recent FreeBSD commits which come to mind. They are detailed below, with links to three different repos.

The code can easily cope with a delete action. That is straight forward.  The first commit listed below is a delete. It was handled properly by both https://devgit.freshports.org/devel/py-trio/ and https://dev.freshports.org/devel/py-trio/

The rename is harder.  I am not sure how to detect that via code. With subversion, the website got it right: https://dev.freshports.org/net/kdav/  With git, it did not, with both the original (https://devgit.freshports.org/net/kdav/) and the copy (https://devgit.freshports.org/net/kf5-kdav/) existing.

Those commits are: 

* Add devel/py-trio: Friendly Python library for async concurrency and I/O
** subversion commit: https://svnweb.freebsd.org/ports?view=revision&revision=542773
** github commit: https://github.com/freebsd/freebsd-ports/commit/50e90b8e07fe7a2df9501714c0114d73fa32438f
** FreeBSD git commit: https://cgit-beta.freebsd.org/ports/commit/?id=44b2876caf1f56d6e940a329a2f8e06724fd621f

* Update KDE Framewokrs to 5.72 ( referenced in the original issue message, but not named as such)
** subversion commit: https://svnweb.freebsd.org/ports?view=revision&revision=542761
** github commit: https://github.com/freebsd/freebsd-ports/commit/d016c9140a6e4b7627d26485926a659f2686185d
** FreeBSD git commit: https://cgit-beta.freebsd.org/ports/commit/?id=ed6418531fb2e8a1fbee24f381a5109cd77bda7a

**Comment by dlangille** [comment]
Looking at the log for `nvi2-port` mentioned above.

Let's look for mentions of delete in the log

```
[dan@dev-ingress01:~/message-queues/recent] $ grep -i delete 2020.07.27.01.58.35.59306.txt.loading 
# # # # Deleting deleted ports # # # #
# # # # Finished deleting deleted ports # # # #
# # # # Resurrecting deleted ports # # # #
```

That is the code looking for ports which were deleted during this update process.

```
found a deleted port: port='nvi2-port', port_id='59576', element_id='1063362'
```
It found one.

```
# # # # Finished resurrecting deleted ports # # # #
```

But there were no file modified for that delete port, so it's a straight delete. Nothing more to do. No deleted ports to resurrect. This is the code checked for anomalies and finding nonw.

The rest is not relevant for our purposes.

```
about to delete port_dependencies for id 59577
sql is DELETE FROM port_dependencies WHERE port_id = 59577
sql is DELETE FROM generate_plist WHERE port_id = 59577;
update_package_flavors: first step, delete any existing flavors
sql is select PackageFlavorsDelete(59577)
This port is deleted: not refreshing.
This port is deleted: not saving.
[dan@dev-ingress01:~/message-queues/recent] $ 

```

**Comment by dlangille** [comment]
I've decided to go with `Delete` & `Add` instead of `Rename`, mostly because of the existing database design.

- https://news.freshports.org/2020/07/29/git-changing-libraries-gave-us-new-xml-options/
- https://news.freshports.org/2020/07/30/for-git-commits-which-is-better-rename-a-to-b-or-delete-a-add-b/
