### ISSUE TITLE
rewrite git-to-freshports-xml.py using devel/py-pygit2

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#24]
re https://github.com/FreshPorts/git_proc_commit/blob/master/git-to-freshports/git-to-freshports-xml.py

I'm getting feedback from bapt and manu that [devel/py-pygit2](https://www.freshports.org/devel/py-pygit2/) is the python interface of libgit2 and we would be better off using that library.  See https://www.pygit2.org

see also https://github.com/iterative/dvc/issues/2215

Is anyone available to do this rewrite please?

**Comment by skozlov404** [comment]
I'm on it

**Comment by dlangille** [comment]
Thank you.  I just started playing with it and I'm getting confused by diffs and how to extract the file information from them.

**Comment by skozlov404** [comment]
I've made a change, but:

- I find pygit2 much more difficult to work with than GitPython. The interface is very low-level and C-like, the documentation is incomplete.
- I've adjusted the unit tests but still, I'd ask you @dlangille  to check if the output of the old and the new code is similar.

**Comment by dlangille** [comment]
Thank you for this. I'll look soon.
