### ISSUE TITLE
getting correct branch for non-head commits

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#32]
I tried processing a FreeBSD src commit not on head (i.e. on a branch).

I used: https://github.com/freebsd/freebsd/commit/d4503c9ddb578727c30194afe2f042da77b1859b

The XML generated is:

```
<?xml version='1.0' encoding='UTF-8'?>
<UPDATES Version="1.4.0.0">
  <UPDATE>
    <DATE Year="2020" Month="8" Day="15"/>
    <TIME Timezone="UTC" Hour="17" Minute="2" Second="23"/>
    <OS Repo="src" Id="FreeBSD" Branch="master"/>
    <LOG>MFC r351783:

Unbreak Linux binaries linked against new glibc, such as the ones
from recent Ubuntu versions.  Without it they segfault on startup.

Sponsored by:   The FreeBSD Foundation</LOG>
    <PEOPLE>
      <UPDATER Handle="trasz &lt;trasz@FreeBSD.org&gt;"/>
    </PEOPLE>
    <COMMIT Hash="d4503c9ddb578727c30194afe2f042da77b1859b" HashShort="d4503c9" Subject="MFC r351783:" EncodingLoses="false" Repository="src"/>
    <FILES>
      <FILE Action="Modify" Path="sys/amd64/linux/linux_sysvec.c"/>
    </FILES>
  </UPDATE>
</UPDATES>
```

As shown, the branch is `master`. I expected `stable/12` based on the github link shown above.

This is how I invoked the script:

git-to-freshports-xml.py --repo src --path ~ingress/repos/freebsd --single-commit d4503c9ddb578727c30194afe2f042da77b1859b --spooling ~ingress/message-queues/spooling/ --output ~ingress/message-queues/testing

At ~ingress/repos/freebsd I have a clone of https://github.com/freebsd/freebsd

**Comment by dlangille** [comment]
@skozlov404 can you help with this please?

**Comment by skozlov404** [comment]
@dlangille I've made a change, but tt increases the processing time substantially since the branch lookup is slow. There may be a better way of doing this, but I'd like to ask you to try the code to check if it does what you want and if the increase in processing time is bearable for your use case.
