### ISSUE TITLE
--first-parent : useful or not?

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#35]
@skozlov404 I've been told that `--first-parent` might be useful for us.

*  if you don't use it, it will cause commits to the vendor branches show up instead of just the merge commit
* you likely want --first-parent, it prevents wandering off the actual branch and onto little chains of side commits that were part of a merge

Examples:

```
[dan@testgit-ingress01:/var/db/ingress/repos/src] $ git rev-list 3cc0c0d66a065554459bd2f9b4f80cc07426464a..HEAD | wc -l
    1305


[ingress@testgit-ingress01 ~/repos/src]$ git rev-list --first-parent 3cc0c0d66a065554459bd2f9b4f80cc07426464a..HEAD | wc -l
    1291
```

**Comment by skozlov404** [comment]
I'll look into it this week

**Comment by skozlov404** [comment]
Change ready, please test when able.

**Comment by dlangille** [comment]
This seems to be working well.  Thank you.
