### ISSUE TITLE
using syslog

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#4]
@skozlov404 Can you help me adjust this to log via syslog? I've been reading but unable to see the easy solution. I can to log using local3 facility please.

**Comment by skozlov404** [comment]
Sure, I'll look into that on the weekend.

**Comment by skozlov404** [comment]
Do you want that to be _instead_ of the stderr logging, with one, or do you want some kind of flag to be able to switch the behavior?

**Comment by dlangille** [comment]
Instead of stderr please.  I would rather have everything in syslog.

**Comment by skozlov404** [comment]
@dlangille please check out #5

**Comment by dlangille** [comment]
@skozlov404 That was merged and is working nicely.  Thank you. Please do no underestimate how much your contributions mean to me and to the project.
