### ISSUE TITLE
git has both type M and type T?

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#6]
I just noticed at https://github.com/FreshPorts/git_proc_commit/blob/362cd4ec74388b1aac153a6398fbf6e1b4867cb3/git-to-freshports/git-to-freshports-xml.py#L108

```
            else:  # M and T types
                ET.SubElement(files, 'FILE', Action='Modify', Path=file_change.a_path)
```

There are two types and both are modify? /cc @skozlov404

**Comment by skozlov404** [comment]
It seems 'T' is for when the file is changed to a symlink or vice-versa. Here's what I could find:
[man git-diff](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203)
[stackoverflow](https://stackoverflow.com/questions/8691199/what-does-t-mean-in-git-status-it-isnt-in-the-man-page)
